baseURL = 'https://zhisme.com/'
languageCode = 'en-us'
title = '@zhisme :: signal over noise'
theme = 'zhisme-blog'
enableRobotsTXT = true

[params]
  description = "A blog about software engineering and developer philosophy."
  keywords = ["software", "engineering", "programmer life", "philosophy", "pragmatic engineer", "zhisme"]
  disqusShortname = "zhisme"

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
[markup.highlight]
  noClasses = false
  codeFences = false
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
