name: Hugo

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'

      - name: Build site
        run: hugo --minify

      - name: Verify build output
        run: |
          if [ ! -d "public" ]; then
            echo "Error: public directory not found"
            exit 1
          fi
          if [ ! -f "public/index.html" ]; then
            echo "Error: index.html not found in public directory"
            exit 1
          fi
          echo "Build verification successful!"
