name: Deploy Hugo site to VPS

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'

      - name: Build site
        run: hugo --minify

      - name: Clean remote folder
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 165.22.80.158
          username: zh
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/blog/*

      - name: Copy site via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 165.22.80.158
          username: zh
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "public/*"
          target: "/var/www/blog"
